services:
  database:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://root:password@database:27017/

  auth_service:
    build:
      context: auth_service
    ports:
      - 8001:8000
    restart: always
    environment:
      DATABASE_URI: mongodb://root:password@database:27017/auth_service

  task_tracker:
    build:
      context: task_tracker
    ports:
      - 8002:8000
    environment:
      DATABASE_URI: mongodb://root:password@database:27017/task_tracker

  frontend:
    build:
      context: frontend
    ports:
      - 8000:8000
    environment:
      BACKEND_URL: http://backend:8000/
      AUTH_SERVICE_URL: http://auth_service:8000/

volumes:
  database: