# generated by datamodel-codegen:
#   filename:  1.json
#   timestamp: 2022-10-15T15:19:28+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class UserDeleted(BaseModel):
    public_id: str = Field(..., title="Public Id")
