# generated by datamodel-codegen:
#   filename:  1.json
#   timestamp: 2022-10-15T15:16:01+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class TaskShuffleRequested(BaseModel):
    user_id: str = Field(..., title='User Id')
