# generated by datamodel-codegen:
#   filename:  1.json
#   timestamp: 2022-10-15T15:16:36+00:00

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field


class TaskStatus(Enum):
    open = 'open'
    closed = 'closed'


class TaskUpdated(BaseModel):
    public_id: str = Field(..., title='Public Id')
    user_id: str = Field(..., title='User Id')
    status: TaskStatus
    description: str = Field(..., title='Description')
    jira_id: Optional[str] = Field(None, title='Jira Id')
